---
- name: Install required packages
  loop:
    - tzdata
    - locales
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - locales

- name: Install language packs
  loop: "{{ locales_packs }}"
  ansible.builtin.package:
    name: "{{ item.name if item.name is defined else item }}"
    state: "{{ 'present' if item.state is undefined else item.state }}"
  tags:
    - locales

- name: Generate locale definitions
  loop: "{{ locales_available }}"
  community.general.locale_gen:
    name: "{{ item.name if item.name is defined else item }}"
    state: "{{ 'present' if item.state is undefined else item.state }}"
  tags:
    - locales

- name: Write default locale
  ansible.builtin.template:
    src: locale.j2
    dest: /etc/default/locale
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - locales

...
